/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agua.telainicial;

import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;

/**
 *
 * @author Gabriel
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }
    //private final Icon icons =  new ImageIcon( Graficomerda.png );
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        grafico = new javax.swing.JLabel();
        BotaoAtualizar1hora = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agua/telainicial/Graficomerda.png"))); // NOI18N

        BotaoAtualizar1hora.setText("1hora");
        BotaoAtualizar1hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizar1horaActionPerformed(evt);
            }
        });

        jButton1.setText("1dia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("30dias");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoAtualizar1hora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BotaoAtualizar1hora, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAtualizar1horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizar1horaActionPerformed
        
        String names[];
        String numeros = null;
        ArrayList al = new ArrayList();
        names = new String[] {"Dia1","Dia2","Dia3","Dia4","Dia5","Dia6","Dia7","Dia8","Dia9","Dia10","Dia11","Dia12","Dia13","Dia14","Dia15","Dia16","Dia17","Dia18","Dia19","Dia20"};
        int y = 0;
        try{
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            BufferedReader br = new BufferedReader(new FileReader("c:/leiturasTeste.txt"));
            while(br.ready()){
                // trocar isso por um for pra ler valores necessarios para uma hora
                String linha = br.readLine();
                int j = Integer.parseInt(linha);
                ds.addValue(j, "media", names[1]);
                System.out.println(linha);
            }
            br.close();
            JFreeChart graficoPlotado = ChartFactory.createLineChart("Meu Grafico", "Dia","Valor", ds, PlotOrientation.VERTICAL, true, true, false);
            try {
                System.out.println("Ta imprimindo ");
                OutputStream png = new FileOutputStream("Graficomerda2.png");
                ChartUtilities.writeChartAsPNG(png, graficoPlotado, 2000, 2000);
                png.close();
                
            }catch(IOException io) {
                System.out.println("ERRO IMBECIL");
            }
            

        }catch(IOException ioe){
                ioe.printStackTrace();
        }
        grafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("Graficomerda2.png")));
       
    }//GEN-LAST:event_BotaoAtualizar1horaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String names[];
        String numeros = null;
        ArrayList al = new ArrayList();
        names = new String[] {"Dia1","Dia2","Dia3","Dia4","Dia5","Dia6","Dia7","Dia8","Dia9","Dia10","Dia11","Dia12","Dia13","Dia14","Dia15","Dia16","Dia17","Dia18","Dia19","Dia20"};
        int y = 0;
        try{
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            BufferedReader br = new BufferedReader(new FileReader("c:/leiturasTeste.txt"));
            while(br.ready()){
                
                // trocar isso por um for pra ler valores necessarios para um dia
                String linha = br.readLine();
                int j = Integer.parseInt(linha);
                ds.addValue(j, "media", names[1]);
                System.out.println(linha);
            }
            br.close();
            JFreeChart graficoPlotado = ChartFactory.createLineChart("Meu Grafico", "Dia","Valor", ds, PlotOrientation.VERTICAL, true, true, false);
            try {
                System.out.println("Ta imprimindo ");
                OutputStream png = new FileOutputStream("Graficomerda2.png");
                ChartUtilities.writeChartAsPNG(png, graficoPlotado, 2000, 2000);
                png.close();
                
            }catch(IOException io) {
                System.out.println("ERRO IMBECIL");
            }
            

        }catch(IOException ioe){
                ioe.printStackTrace();
        }
        grafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("Graficomerda2.png")));
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String names[];
        String numeros = null;
        ArrayList al = new ArrayList();
        names = new String[] {"Dia1","Dia2","Dia3","Dia4","Dia5","Dia6","Dia7","Dia8","Dia9","Dia10","Dia11","Dia12","Dia13","Dia14","Dia15","Dia16","Dia17","Dia18","Dia19","Dia20"};
        int y = 0;
        try{
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            BufferedReader br = new BufferedReader(new FileReader("c:/leiturasTeste.txt"));
            while(br.ready()){
                
                // trocar isso por um for pra ler valores necessarios para um mes
                String linha = br.readLine();
                int j = Integer.parseInt(linha);
                ds.addValue(j, "media", names[1]);
                System.out.println(linha);
            }
            br.close();
            JFreeChart graficoPlotado = ChartFactory.createLineChart("Meu Grafico", "Dia","Valor", ds, PlotOrientation.VERTICAL, true, true, false);
            try {
                System.out.println("Ta imprimindo ");
                OutputStream png = new FileOutputStream("Graficomerda2.png");
                ChartUtilities.writeChartAsPNG(png, graficoPlotado, 2000, 2000);
                png.close();
                
            }catch(IOException io) {
                System.out.println("ERRO IMBECIL");
            }
            

        }catch(IOException ioe){
                ioe.printStackTrace();
        }
        grafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("Graficomerda2.png")));
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAtualizar1hora;
    private javax.swing.JLabel grafico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
